### ISSUE TITLE
Static HTML builds for sites with `folders: true` put JSON in wrong place

### ISSUE THREAD

**Issue by agoose77** [jupyter-book/mystmd#1635]
The present MyST docs refer to the ability to view the structured data of a page from the URL:
https://mystmd.org/guide/website-metadata#page-document-metadata-as-json

With the advent of the new `folders` option for the book theme, this is not always valid; as per https://github.com/jupyter-book/mystmd/issues/1635#issuecomment-2473632863 we intentionally leave the JSON for pages at the non-folder slug path. 

How should we resolve this? Do we need to update the docs? Or, is this a bug?

If the docs need updating, can we consider this issue both a bug (docs) and a feature request (embed information in the HTML about the location of the JSON?)

See the referenced lines:
https://github.com/jupyter-book/mystmd/blob/d8566d4e1f813163a81698b1b14a38f9fb8b2e11/packages/myst-cli/src/build/html/index.ts#L38-L46

**Comment by rowanc1** [comment]
This is intentional, the static sites data url remains the slug for hover references, not the folder version.

**Comment by agoose77** [comment]
@rowanc1 I quite like that change from the perspective that the theme options don't break URLs to data. But, I wonder if we need a way to link to the data from the HTML page now? E.g.

If I want to cross-link to a heading on [Chris' blog](https://chrisholdgraf.com/blog/2024/blog-list), before the URL folders option I could effectively inspect the URL for the xref path, and then hover for the identifier slug (although I have a feeling that's not the case if the escaped identifier != the HTML identifier). With folders, it's even less clear. 

Have you guys given this any thought yet? We can discuss in the MyST meeting today. Some initial non-mutually-exclusive ideas:

1. Embed the link to the data in the HTML page via a meta tag. 
2. Add a new CLI that translates `foo/bar/baz.html` into `baz.json` e.g. `myst-data https://chrisholdgraf.com/blog/2024/blog-list#use-the-myst-sandbox-to-determine-what-ast-to-generate`
  This would act on HTML IDs, not identifiers.

tbc.

**Comment by choldgraf** [comment]
Can you re-write this issue so that it's clear what the user-facing impact is? That way we can prioritize this against the other stuff on our plate. I think that's a precursor to digging into potential fixes in meetings - we need to be able to compare the value to users of this issue vs. [the other items in beta/alpha columns](https://github.com/orgs/jupyter-book/projects/1?query=sort:updated-desc+is:open)

**Comment by agoose77** [comment]
@choldgraf this is a MyST-wide issue for anyone using the book theme, not just Jupyter Book! I've placed it in the `needed-for-beta` column based on a prior, but I expect that we can refine those details at the MyST meeting today.

To answer your question above, yes -- this is mainly an inference problem and a docs problem (see updated description).

**Comment by choldgraf** [comment]
Ah got it - it is now clearer why that's going to confuse users. 

That said my feeling is that the broader issue to track is an enhancement like "improve the UX around discovering and accessing page AST" and this issue is one part of it.

For JB2, All of this feels "nice to have" rather than "critical" for now though, especially since none of this functionality exists in jupyter book already so there will be no regressions

**Comment by agoose77** [comment]
Based on our meeting today, we should be able to refine what the intention is, to determine next steps.
