### ISSUE TITLE
Support folder hierarchies and nested files in URLs without flattening them

### ISSUE THREAD

**Issue by nthiery** [jupyter-book/mystmd#670]
When building a web site, nested file names are flattened and replaced
with slugs:

https://mystmd.org/guide/table-of-contents#nesting-of-files-in-urls

While I can see the value for the end-user (simple urls), there are use cases
where this is detrimental, as the nested file name actually carries semantic.

For example, in my [course](https://Nicolas.thiery.name/Enseignement/Info111/),
the name of a document, says `/Solutions/Semaine3/foo.html` tells that
this is a solution for notebook foo of week 3. While `Devoirs/Semaine3/foo.html`
is the original assignment. This also helps the user match the pages on the
web with the notebooks that they have dowloaded separately.

## Proposal

Provide a configuration option `flatten_filename=true/false`, with `true` as default
value, to enable or disable flattening of file names.

Provide a configuration option 'transform_filename=true/false`, with `true` as default
value, to enable or disable [file name transformation](https://mystmd.org/guide/table-of-contents#filename-transformations).

When both options are set to false, one recovers JupyterBook's behavior.

**Comment by nthiery** [comment]
I believe this is my last blocker for migrating my course notes to myst :-)

Next in line: a course starting in January:

https://nicolas.thiery.name/Enseignement/IntroScienceDonnees/

Thanks in advance!

**Comment by choldgraf** [comment]
Could I signal-boost this one? Is it a particularly complicated one to implement? I ask because I think this is one of the only remaining "hard blockers" for any pre-existing users of Jupyter Book or Sphinx, given that currently, switching to MyST will break everybody's URLs.

**Comment by agoose77** [comment]
Talking to @choldgraf, another point to consider is the ability to preserve existing links. If we implement a jb1 slug scheme, then we could easily ensure that no links break.

However this is not necessarily a requirement.

**Comment by rowanc1** [comment]
That is links in the table of contents?

I have talked to @fwkoch and we are going to do some planning on this this week, and ideally get it over the line next week.

**Comment by agoose77** [comment]
I mean that should a user have some uri to `foo/bar.md`, we should maybe have a mode for preserving that (which goes beyond supporting folders to ensuring that the entire url for a page is identical).

Maybe it should be a configurable setting.

**Comment by choldgraf** [comment]
As a few driving examples:

- Jupyter Book's default HTML builder uses `.html` files, here's what they look like: `https://jupyterbook.org/en/stable/publish/gh-pages.html`
- Jupyter Book also allows for `dirhtml` builders, which look like this: `https://compass.2i2c.org/people/expectations/`

The concerns @agoose77 is voicing are that:

- Folks using the `html` builder will have any direct links to their docs break, because `foo.html` will become `foo/index.html`
- Folks using the `dirhtml` builder _might_ have direct links to their docs break, if the sluggification conventions change (not sure whether this is true or not, but things like `My page.md` getting renamed to `my_page/` vs. `my-page/`

**Comment by agoose77** [comment]
We also might want to do a pass in adding explicit '.html' to our static file urls - right now we leave that to the file server (so python's http server doesn't work)

**Comment by rowanc1** [comment]
This will be possible in the next version of the mystmd/theme.

`myst clean --templates`

```yaml
site:
    options:
        folders: true
```

Let us know how it works for y'all!

**Comment by nthiery** [comment]
Nice! Looking forward to get to try it!

**Comment by fperez** [comment]
Quick question - does the option need to be given explicitly? I'd hazard that the "natural" expectation is that a set of existing folders gets mapped to the same hierarchy by default, and that flattening is an additional operation that should be requested manually.

Regardless, huge thanks for this, it's a really important improvement and much appreciated!

**Comment by rowanc1** [comment]
As we enable new workflows around tutorials, courses and books, we should define those defaults to make sense for those spaces. The docs for how that will work are here:
https://next.jupyterbook.org/build-websites#declaring-a-table-of-contents

JuptyerBook will define presets that are inherited, and I agree that this should be turned to `true` there.

This is also quite a powerful feature for inheriting community practices, author metadata, etc. Some ideas around math snippets are here as an example:
https://doi.org/10.62329/YERW1834

MyST has grown up as a way to publish scientific articles, where the author doesn't have control over the URL paths and structure (e.g. requesting custom URL structure on bioRxiv or nature is not a thing), which is why this is designed the way it is. Also the zen of python's "flat is better than nested" is rattling around when thinking about the data structures behind the scenes, which continue to be flat even with folders enabled! This helps when composing sites at a data layer. Regardless, easy to override in the theme and likely the default in jupyter-book, which will be geared more for tutorials and courses.

**Comment by fperez** [comment]
Thanks so much @rowanc1 for the detailed explanation, as it makes a lot of sense, and I'm actually glad we have both options, as the use cases are both legitimate and important. But I appreciate your care in providing clarity and detail for the motivation!

**Comment by choldgraf** [comment]
I feel like we shoudl include @rowanc1 's explanation above in the docs as a little footnote or something, it is very clear and helpful IOM

**Comment by ryanlovett** [comment]
> Let us know how it works for y'all!

It worked, thanks!

**Comment by nthiery** [comment]
Hi! I just got to test, and it's much better indeed! Thanks a lot!

I still get some file name rewriting:
- file and directory names are rewritten to lowercase
- accented characters are stripped: e.g. `combinatoire-énumérative` is rewritten to `combinatoire-num-rative`

I would prefer no rewriting at all as in Jupyter-Book, to ensure a 1-1 trivial correspondence with file names.
This would also ensure a better compatibility with Jupyter-Book.

Should this be a separate ticket?

**Comment by choldgraf** [comment]
Please open a separate ticket - thanks!

**Comment by rowanc1** [comment]
Thanks @nthiery - a separate ticket would be awesome. I think you are officially the person in charge of finding everywhere we screw up `é --> e` in new features. Thank you for your patience. :)

**Comment by nthiery** [comment]
@rowanc1 : my pleasure; that's what international collaborative development is here for: it takes the diversity of a (global) village to raise a tool! I hope we have users around with even more complicated charsets to further shake out the bugs.

**Comment by parmentelat** [comment]
Hiya
I must be missing something, as I tried to use this setting but that did not work as I expected

So, my config file is here
https://github.com/flotpython/jupyterlab-examples/blob/main/notebooks/myst.yml#L39

And here is how it yields under GH pages
https://flotpython.github.io/jupyterlab-examples/images-nb

Even though the source markdown is in this file
https://github.com/flotpython/jupyterlab-examples/blob/main/notebooks/1-01-images-nb.md

here's the - almost - same content published with jb1 at rtd, where the URL did match the filename
https://jupyterlab-examples.readthedocs.io/en/jb1/1-01-images-nb.html

and to be totally clear I was expecting the GH Pages URL to have been
https://flotpython.github.io/jupyterlab-examples/1-01-images-nb.md

**Comment by nthiery** [comment]
Yeah ... I had the same implicit expectation and created #1648 for that (see above). Please upvote it :-)
